
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.13 (Homebrew)
-- Dumped by pg_dump version 14.13 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: boards; Type: TABLE; Schema: public; Owner: java_proj
--

CREATE TABLE public.boards (
                               id bigint NOT NULL,
                               date_created timestamp(6) with time zone NOT NULL,
                               matrix_data text NOT NULL,
                               owner_id bigint
);


ALTER TABLE public.boards OWNER TO java_proj;

--
-- Name: board_id_seq; Type: SEQUENCE; Schema: public; Owner: java_proj
--

ALTER TABLE public.boards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: java_proj
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              email character varying(255),
                              username character varying(255) NOT NULL,
                              date_created timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO java_proj;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: java_proj
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Data for Name: boards; Type: TABLE DATA; Schema: public; Owner: java_proj
--

COPY public.boards (id, date_created, matrix_data, owner_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: java_proj
--

COPY public.users (id, email, username, date_created) FROM stdin;
14	\N	allen505	2024-12-15 12:26:19.352836
\.


--
-- Name: board_id_seq; Type: SEQUENCE SET; Schema: public; Owner: java_proj
--

SELECT pg_catalog.setval('public.board_id_seq', 7, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: java_proj
--

SELECT pg_catalog.setval('public.users_id_seq', 15, true);


--
-- Name: boards board_pkey; Type: CONSTRAINT; Schema: public; Owner: java_proj
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT board_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: java_proj
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: boards fk84tpcdndvu39hefevsc0mf5ov; Type: FK CONSTRAINT; Schema: public; Owner: java_proj
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT fk84tpcdndvu39hefevsc0mf5ov FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

